name: ready_ecommerce
description: A new Flutter project.
publish_to: none
version: 1.0.5+7
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  connectivity_wrapper: ^1.1.4
  app_settings: ^5.1.1
  gap: ^3.0.1
  page_transition: ^2.1.0
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  device_preview: ^1.1.0
  flutter_form_builder: ^10.2.0
  pinput: ^5.0.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  dotted_border: ^2.1.0
  geolocator: ^13.0.1
  image_picker: ^1.0.7
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.20.0
  tuple: ^2.0.2
  intl_utils: ^2.8.11
  flutter_localizations:
    sdk: flutter
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.0
  auto_size_text: ^3.0.0
  # flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.5
  flutter_animate: ^4.5.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  flutter_inappwebview: ^6.0.0
  # open_file_plus: ^3.4.1+1
  flutter_timer_countdown: ^1.0.7
  slide_countdown: ^2.0.2
  country_code_picker: ^3.1.0
  carousel_slider: ^5.0.0
  webview_flutter: ^4.10.0
  chewie: ^1.9.2
  shimmer: ^3.0.0
  share_plus: ^10.1.4
  pusher_channels_flutter: ^2.5.0
  open_file: ^3.5.10
  fluttertoast: ^8.2.12
  change_app_package_name: ^1.5.0
  flutter_file_downloader: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0
#  hive_generator: ^2.0.1
#  analyzer: ^6.4.1

# dependency_overrides:
#   # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
#   flutter_inappwebview_android:
#     git:
#       url: https://github.com/holzgeist/flutter_inappwebview
#       path: flutter_inappwebview_android
#       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/json/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/font/Mulish-Regular.ttf
        - asset: assets/font/Mulish-Medium.ttf
        - asset: assets/font/Mulish-bold.ttf
        - asset: assets/font/Mulish-light.ttf
        - asset: assets/font/Mulish-Italic.ttf
